/** Permission keys — must match API `permissions.constants.ts`. */
export const PERM = {
  settings: {
    users: { view: 'settings.users.view', manage: 'settings.users.manage' },
    roles: { view: 'settings.roles.view', manage: 'settings.roles.manage' },
    permissions: {
      view: 'settings.permissions.view',
      manage: 'settings.permissions.manage',
    },
  },
  dashboard: { view: 'dashboard.view' },
  insights: { view: 'insights.view' },
  orders: { view: 'orders.view', update: 'orders.update' },
  productFeedback: {
    view: 'product-feedback.view',
    manage: 'product-feedback.manage',
  },
  products: { view: 'products.view', manage: 'products.manage' },
  sizePresets: { view: 'size-presets.view', manage: 'size-presets.manage' },
  categories: { view: 'categories.view', manage: 'categories.manage' },
  brands: { view: 'brands.view', manage: 'brands.manage' },
  banners: { view: 'banners.view', manage: 'banners.manage' },
  inventory: { view: 'inventory.view', manage: 'inventory.manage' },
  users: { view: 'users.view', coinsManage: 'users.coins.manage' },
  finance: { view: 'finance.view', export: 'finance.export' },
  rewards: { view: 'rewards.view', manage: 'rewards.manage' },
  coinGifts: { view: 'coin-gifts.view', manage: 'coin-gifts.manage' },
  coinLedger: { view: 'coin-ledger.view' },
  campaigns: { view: 'campaigns.view', manage: 'campaigns.manage' },
  promotions: { view: 'promotions.view', manage: 'promotions.manage' },
  segments: { view: 'segments.view', manage: 'segments.manage' },
  broadcasts: { view: 'broadcasts.view', manage: 'broadcasts.manage' },
  automations: { view: 'automations.view', manage: 'automations.manage' },
  notifications: { view: 'notifications.view' },
} as const;
