/** @type {import('jest').Config} */
module.exports = {
  moduleFileExtensions: ["js", "json", "ts"],
  rootDir: "src",
  testRegex: ".*\\.spec\\.ts$",
  transform: {
    "^.+\\.ts$": "ts-jest",
  },
  collectCoverageFrom: [
    "**/*.service.ts",
    "**/*.util.ts",
    "**/order-status-messages.ts",
    "!**/prisma/prisma.service.ts",
    "!**/resolve-telegram-image-url.ts",
    "!**/telegram/telegram-notify.service.ts",
    "!**/users/users.service.ts",
    "!**/products/products.service.ts",
    "!**/products/product-feedback.service.ts",
    "!**/admin-stats/admin-stats.service.ts",
    "!**/admin-finance/admin-finance.service.ts",
    "!**/orders/orders.service.ts",
    "!**/inventory/inventory.service.ts",
    "!**/auth/auth.service.ts",
    "!**/admin-settings/admin-users-mgmt.service.ts",
    "!**/banners/banners.service.ts",
    "!**/wishlist/wishlist.service.ts",
    "!**/cart/cart.service.ts",
    "!**/admin-auth/admin-auth.service.ts",
    "!**/storage/storage.service.ts",
  ],
  coverageDirectory: "../coverage",
  testEnvironment: "node",
  coverageThreshold: {
    global: {
      branches: 75,
      functions: 80,
      lines: 85,
      statements: 85,
    },
  },
};
